Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.database.usersTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${file(./config/scale.config.yml):dynamoProvisionedReadCapacity.${self:provider.stage}}
        WriteCapacityUnits: ${file(./config/scale.config.yml):dynamoProvisionedWriteCapacity.${self:provider.stage}}
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: TRUE
